### ISSUE TITLE
Checklist do projeto

### ISSUE THREAD

**Issue by beatrizgomess** [beatrizgomess/GCMS-2023-1-Lilian-Gomes#2]
Para fazer: @beatrizgomess 

- [ ] Instalar Git Localmente
- [ ] Criar projeto local
- [ ] Criar repositorio local e realizar commits
- [ ] Subir alterações no repositório da turma

@ramidedantas
